apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
replicas:
  - name: s2-worker
    count: 1
patches:
  - target: {kind: Job, name: s2-orchestrate}
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "1"
